BeHappy\SyliusManufacturerPlugin\Entity\Manufacturer:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
    properties:
        code:
            - NotBlank: ~
        images:
            - Valid: ~
        translations:
            - Valid: ~
