BeHappy\SyliusManufacturerPlugin\Entity\Product:
    type: mappedSuperclass
    table: sylius_product
    manyToOne:
        manufacturer:
            targetEntity: BeHappy\SyliusManufacturerPlugin\Entity\Manufacturer
            inversedBy: products
